# Generated by Django 3.2.8 on 2021-10-19 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_auto_20211018_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_success', models.CharField(max_length=20)),
                ('session_id', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=20)),
                ('amount_total', models.IntegerField()),
                ('payment_status', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
