# Generated by Django 3.2.8 on 2021-10-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forum',
            name='premium_only',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
