# Generated by Django 3.2.8 on 2021-10-15 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20211015_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='forum',
            new_name='discussion',
        ),
    ]
