# Generated by Django 3.2.8 on 2021-10-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_rename_forum_comment_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
        migrations.AddField(
            model_name='forum',
            name='forum_name',
            field=models.CharField(default='anonymous', max_length=20, unique=True),
        ),
    ]
