# Generated by Django 3.2.8 on 2021-10-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_forum_forum_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='picture',
            field=models.ImageField(default='post_pics/default.png', upload_to='post_pics'),
        ),
    ]
